### ISSUE TITLE
HA / Gardena Integration doesn't work

### ISSUE THREAD

**Issue by trtmr** [py-smart-gardena/hass-gardena-smart-system#5] opened 2020-05-31 18:39 UTC
Hi all,

I'm running HA 0.110.4 and installed HACS and Garden Integration today. I have configured everything as described in the guide.

Following errors coming up in HA log:

No. 1:

Logger: gardena.smart_system
Source: custom_components/gardena_smart_system/__init__.py:88 
First occurred: 20:27:47 (1 occurrences) 
Last logged: 20:27:47

403 : {'message': 'Forbidden'}

No. 2:

Logger: custom_components.gardena_smart_system
Source: custom_components/gardena_smart_system/__init__.py:91 
Integration: Gardena Smart System (documentation) 
First occurred: 20:27:47 (1 occurrences) 
Last logged: 20:27:47

No locations found

No 3:

Logger: homeassistant.config_entries
Source: custom_components/gardena_smart_system/__init__.py:92 
First occurred: 20:27:48 (1 occurrences) 
Last logged: 20:27:48

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/config/custom_components/gardena_smart_system/__init__.py", line 51, in async_setup_entry
    await hass.async_add_executor_job(gardena_system.start)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 92, in start
    raise Exception("No locations found")
Exception: No locations found

Any idea why this isn't working? Do I need to configure something in edition in swagger options on Husqvarna API?

Thanks & regards

**Comment by osks** [comment] 2020-05-31 18:43
Do you have the Gardena app and have added/included device, and are using the same username/password as there?

**Comment by trtmr** [comment] 2020-05-31 18:46
When testing in terminal, I get the following reply:

{"error":"invalid_grant","error_description":"The provided access grant is invalid, expired, or revoked."}DEVICENAME-13:~ benutzer$

@osks Yes, I can log in to the Gardena App, also logged in to Husqvarna website using same email/pw

**Comment by trtmr** [comment] 2020-05-31 19:06
If there is anything else I can provide, which helps navigate to the problem, please let me know ;)

**Comment by grm** [comment] 2020-05-31 22:01
Does your application id matches the application key from https://developer.husqvarnagroup.cloud/apps ?

**Comment by osks** [comment] 2020-06-01 07:05
And did you connect the APIs?

**Comment by newlund** [comment] 2020-06-01 08:19
I'm running the latest version (commit ebb01e52b6731c9700a01fcef4ba5867f0121c16)
Get this when trying to add the integration in HA:

Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 70, in async_step_user
    user_input[CONF_CLIENT_ID])
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 168, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 163, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 156, in __response_has_errors
    raise Exception(msg)
Exception: Forbidden (hint: did you 'Connect an API' in your Application?)

I have connected the APIs in "My application"
![image](https://user-images.githubusercontent.com/1943085/83390031-6975e000-a3f1-11ea-999e-2b58d35ed07d.png)

**Comment by pdecat** [comment] 2020-06-01 15:29
Same issue here, apparently new API keys do not work immediately, see https://github.com/openhab/openhab-addons/issues/7169#issuecomment-636677619

Failing using curl or the [online API tools](https://developer.husqvarnagroup.cloud/apis/GARDENA+smart+system+API#/swagger) too:

```
curl -i -X GET "https://api.smart.gardena.dev/v1/locations" -H  "accept: application/vnd.api+json" -H  "X-Api-Key: f993435b-****-****-****-********" -H  "Authorization: Bearer eyJh****G3Ug" -H  "Authorization-Provider: husqvarna"
HTTP/2 403
content-type: application/json
content-length: 23
date: Mon, 01 Jun 2020 15:21:50 GMT
x-amzn-requestid: e54b0b96-****-****-****-********"
x-amzn-errortype: ForbiddenException
x-amz-apigw-id: Nd******=
x-cache: Error from cloudfront
via: 1.1 a93cc4cff5c450718aa682ae0fc55be3.cloudfront.net (CloudFront)
x-amz-cf-pop: CDG50-C1
x-amz-cf-id: Uz******==
```

**Comment by osks** [comment] 2020-06-01 18:09
Thank you for that information! Very helpful!

The API documentation for https://api.smart.gardena.dev/v1/locations does not mention the 403 status code, so it's probably not something that has occurred in testing.

**Comment by ApplesandPears** [comment] 2020-06-01 18:32
> Did you create an application there : https://developer.husqvarnagroup.cloud/apps?
> Does your application id matches the application key from https://developer.husqvarnagroup.cloud/apps ?

Using another user account. Working together with @trtmr .

Husqvarna app created, application key is correct!

**Comment by grm** [comment] 2020-06-01 19:57
Ok, not sure about the reason.

My key was created a long time ago. Can you keep us informed tomorrow if it nwo works for you ? (we'll update the readme accordingly if that is the case)

**Comment by awirtz** [comment] 2020-06-02 14:05
Hi,

just would like to confirm the issue. I have a Gardena Smart account, just today created everything in the developer webplatform at Husqvarna and am now not able to connect the HA integration with my credentials - 403 just like above.

**Comment by sabbatho** [comment] 2020-06-02 16:14
Hi,
I have the same errors as described above with 403 error in logs, and the no location found.
Installed through HACS.
Just wanted to make a comment that i have the same problem.
Have had my Gardena account for a few weeks, but configured the key a couple of hours ago in Husqvarna developer and connected the two apis as described in the installation notes. Tried to redo the integration in Home assistant but have the same errors still.
I'm on version 110.4. And i have restarted Home Assistant after integration added.

**Comment by ApplesandPears** [comment] 2020-06-02 16:26
@grm @osks have you anything configured in the API on the Husqvarna website? 

I am open for a zoom session if we want to do hands on... if this helps... 

Cheers,

**Comment by grm** [comment] 2020-06-02 21:12
Maybe one of you would you agree to send me your creds and API key by mail (from my profile) so i can debug more deeply ?
(you can change them before and will be able to change them afterwards)

Grm

**Comment by awirtz** [comment] 2020-06-03 10:22
FYI, I've tried the "Sample Websocket Client" at https://developer.husqvarnagroup.cloud/apis/GARDENA+smart+system+API#/readme, I can obtain an access token, but the subsequent call to obtain the location also fails with a status code 200 and HTTP Error 403.

The access token I'm getting is rather lengthy and not in the format as seen in the authentication API documentation (i.e. access_token: '1ff71952-53e8-4d19-a837-b4a5f09829be'), might this be the reason?

**Comment by pdecat** [comment] 2020-06-04 07:50
From https://developer.husqvarnagroup.cloud/apis/GARDENA+smart+system+API:

> We are currently experiencing technical difficulties with the Smart Garden API. Our team is actively working to fix the issue. We hope to have this resolved soon. Thank you for your patience.

**Comment by ApplesandPears** [comment] 2020-06-04 11:20
Guys, for everyone who wants to integrate Gardena Smart System into Home Assistant. There is an alternative way of doing this.

Go to "Configuration / Einstellungen" then to "Integrations / Integrationen", click the "+" in the bottom right corner, Search for "HomeKit Controller", Click on it and then choose from the drop down menu the Gardena Smart System. Enter the HomeKit code, printed on the back of the Gardena Smart Gateway - et voilà the Gardena Bridge including all Switches and Sensors is now available in Home Assistant.

From there, if you're an iOS User, you can expose those devices to the HA HomeBridge. 

![image](https://user-images.githubusercontent.com/56008284/83750661-e5785e00-a665-11ea-9abd-15387f43de0f.png)

**Comment by pdecat** [comment] 2020-06-04 13:34
The issue was resolved, affected users need to click the `Renew API key` on the [Home Assistant Gardena app](https://developer.husqvarnagroup.cloud/apps).

See https://github.com/openhab/openhab-addons/issues/7169#issuecomment-638840271

**Comment by dueltschi** [comment] 2020-06-04 14:12
it works perfectly. thanks a lot!

**Comment by sabbatho** [comment] 2020-06-04 14:13
Confirmed, works fine now according to @pdecat's post

**Comment by newlund** [comment] 2020-06-04 14:42
Working for me as well. Thanks! :)

**Comment by lukasvermeer** [comment] 2020-06-04 14:56
+1 Works.

**Comment by grm** [comment] 2020-06-04 14:59
Great news,

I am currently speaking with gardena devs so we can be part of a program about issues. I am not sure what they will be able to provide us to be able to react more quickly !

Btw, thanks a lot @pdecat for the rapid follow up

**Comment by grm** [comment] 2020-06-06 23:22
Thx for the update and the homekit intégration !
It is a pleasure to have positive feedback like this.

I will now close this ticket as the original issue has been solved.
If you want to have a discussion over homekit vs hass-gardena-smart-system, I let you open another ticket ;)

**Closed by grm** 2020-06-06 23:22 UTC
