### ISSUE TITLE
Soon integration will not work anymore in HA

### ISSUE THREAD

**Issue by BogdanRosioru** [py-smart-gardena/hass-gardena-smart-system#221] opened 2024-08-10 17:45 UTC
[home-assistant_gardena_smart_system_2024-08.txt](https://github.com/user-attachments/files/16570431/home-assistant_gardena_smart_system_2024-08.txt)

**Comment by TOBx2** [comment] 2024-08-12 06:38
Duplicate of #217

**Comment by grm** [comment] 2024-09-02 20:19
I closee thos one as it is a duplicate :)

**Closed by grm** 2024-09-02 20:19 UTC
