### ISSUE TITLE
Errors on Startup

### ISSUE THREAD

**Issue by quiqueck** [py-smart-gardena/hass-gardena-smart-system#91] opened 2021-09-04 08:17 UTC
On Startup, the component throws an unhandled error:
`2021-09-04 10:02:22 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x7fa95f6d90>>: on_open() takes 1 positional argument but 2 were given
2021-09-04 10:02:22 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_error of <gardena.smart_system.Client object at 0x7fa95f6d90>>: on_error() takes 2 positional arguments but 3 were given
2021-09-04 10:02:22 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 407, in _callback
callback(self, *args)
TypeError: on_open() takes 1 positional argument but 2 were given
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 322, in run_forever
self._callback(self.on_open)
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 412, in _callback
self.on_error(self, e)
TypeError: on_error() takes 2 positional arguments but 3 were given
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 407, in _callback
callback(self, *args)
TypeError: on_error() takes 2 positional arguments but 3 were given
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 910, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 371, in run_forever
self._callback(self.on_error, e)
File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 412, in _callback
self.on_error(self, e)
TypeError: on_error() takes 2 positional arguments but 3 were given`

I noticed that the the readings of valves are wrong on occasion (shows as closed while they are open), and the temperature/soil sensors are not updated. Not sure if that is related to the startup error..

**Comment by fjepsen** [comment] 2021-09-11 15:01
I think this is a duplicate of or related to this issue: [Sensor not updated #88 ](https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/88?_pjax=%23repo-content-pjax-container)
You have to install 0.2.5b3 Beta.
You can do this from HACS by choosing Install and then Show Beta.

I also have a problem with an old websocket lib which will not get updated automatically.
Perhaps don't have this problem because you are already on Python3.9.
Can please tell me what version of websocket lib is installed in your environment?
I think you can see that in /usr/local/lib/python3.9/site-packages/websocket_client-x.yy.0.dist-info

**Closed** 2021-11-29 20:52 UTC
